rewards:
  common:
    1:
      material: STONE_BRICKS
      min_amount: 16
      max_amount: 64
      weight: 0.5
    2:
      material: STONE_BRICKS
      min_amount: 8
      max_amount: 16
      weight: 0.25
    3:
      material: STICK
      min_amount: 1
      max_amount: 32
      weight: 0.2
    4:
      material: IRON_INGOT
      min_amount: 1
      max_amount: 4
      weight: 0.05
  rare:
    1:
      material: IRON_INGOT
      min_amount: 4
      max_amount: 16
      weight: 1.0
  ultra_rare:
    1:
      material: DIAMOND
      min_amount: 1
      max_amount: 3
      weight: 1.0